#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     IRSeeker,       sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorTL,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorTR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBrush,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorConveyor, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoHingeL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servoHingeR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



void turnLeftDegrees(int degree, int speed)
{
	int tickGoal = degree * 8;
	int tickTest = nMotorEncoder[motorTR];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = speed * -1;
		motor[motorTR] = speed;
		motor[motorBL] = speed * -1;
		motor[motorBR] = speed;

		tickTest = nMotorEncoder[motorTR];
	}
}

void turnRightDegrees(int degree, int speed)
{
	int tickGoal = degree * 8;
	int tickTest = nMotorEncoder[motorTL];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = speed;
		motor[motorTR] = speed * -1;
		motor[motorBL] = speed;
		motor[motorBR] = speed * -1;

		tickTest = nMotorEncoder[motorTL];
	}
}

//void turnDegrees(int degree, int speed)
//{
//	motor[motorBR] = -speed; //turn both motors on at 30 percent power
//  motor[motorBL] = speed;
//  motor[motorTR] = -speed;
//  motor[motorTL] = speed;

//  wait1Msec(500);

//	motor[motorBR] = 0; //turn both motors off
//	motor[motorBL] = 0;
//	motor[motorTR] = 0;
//	motor[motorTL] = 0;
//}

void goInches(int inch, int speed)
{
	int tickGoal = 67 * inch;
	int tickTest = nMotorEncoder[motorBR];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = speed;
		motor[motorTR] = speed;
		motor[motorBL] = speed;
		motor[motorBR] = speed;

		tickTest = nMotorEncoder[motorBR];
	}
}


//void findIr() //Using light sensor
////The darker the environment, the higher the value will be
//{
//	while(SensorValue[IRSeeker] != 5) //While the IR sensor hasn't been found
//	{
//		while(SensorValue[LightSensor] > 60) //change value later. If the light sensor reads grey (the main floor), turn until it finds yellow
//		{
//			motor[motorBR] = -15;
//			motor[motorBL] = 15;
//			motor[motorTR] = -15;
//			motor[motorTL] = 15;
//		}
//		//If the light sensor does read yellow, go forward very slowly to try and find the IR sensor
//		motor[motorBR] = 15;
//		motor[motorTR] = 15;
//		motor[motorBL] = 15;
//		motor[motorTL] = 15;
//	}
//}

void gripGoal()
{
	//Bring the grips down
	servo[servoHingeL] = 90; //CHANGE VALUES LATER
	servo[servoHingeR] = 90;

	//Grip tightens around the goal
	//servo[servoGripL] = 100; //CHANGE VALUES LATER
	//servo[servoGripR] = 0;
}

void ungripGoal()
{
	//Grip loosens around the goal
	//servo[servoGripL] = 0; //CHANGE VALUES LATER
	//servo[servoGripR] = 100;
}

//task main()
//{
//	//goInches(17, 60);
//	//turnRightDegrees(90, 60);
//	//turnLeftDegrees(90, 40);

////	gripGoal();

//}

//1440 ticks per revolution
//4 inch diameter wheel
//12.56 inch circumference
//1440 / 12.56 = 114.6 ticks per inch

//1120 / 12.56 = 89.17 ticks per inch
