#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorPulleyLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorPulleyRight, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorTL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorBrush,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_1,     motorTR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     motorA,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servoHingeL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servoHingeR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servoBasketR,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servoBasketL,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}
void turnLeftDegrees(int degree)
{
	int tickGoal = degree * 14;
	int tickTest = nMotorEncoder[motorBR];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = -60;
		motor[motorTR] = 60;
		motor[motorBL] = -60;
		motor[motorBR] = 60;

		tickTest = abs(nMotorEncoder[motorBR]);

	}
}

void turnRightDegrees(int degree)
{
	int tickGoal = degree * 14;
	int tickTest = nMotorEncoder[motorBR];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = 60;
		motor[motorTR] = -60;
		motor[motorBL] = 60;
		motor[motorBR] = -60;

		tickTest = abs(nMotorEncoder[motorBR]);
	}
}

void goInches(int inch, int speed)
{
	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	int tickGoal = 67 * inch;
	int tickTest = nMotorEncoder[motorBR];

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = speed;
		motor[motorTR] = speed;
		motor[motorBL] = speed;
		motor[motorBR] = speed;

		tickTest = abs(nMotorEncoder[motorBR]);
	}
}

void goBackInches(int inch, int speed)
{

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	int tickGoal = 67 * inch;
	int tickTest = nMotorEncoder[motorBR];

	//move backward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = -speed;
		motor[motorTR] = -speed;
		motor[motorBL] = -speed;
		motor[motorBR] = -speed;

		tickTest = abs(nMotorEncoder[motorBR]);

	}
	motor[motorTL] = 0;
	motor[motorTR] = 0;
	motor[motorBL] = 0;
	motor[motorBR] = 0;
}


void gripGoal()
{
	//Bring the grips down
		servo[servoHingeL] = 0; //CHANGE VALUES LATER
		servo[servoHingeR] = 250;
		wait1Msec(500);

}

void ungripGoal()
{
	//Grip loosens around the goal
		servo[servoHingeL] = 120; //CHANGE VALUES LATER
		servo[servoHingeR] = 120;
		wait1Msec(500);

}

/* TASKS TO DO
	1. Move off of ramp [20 points]
	2. Go to goal
	3. Grab goal
	4. Move goal to parking zone [20 points]
*/

//set robot up backwards
task main()
{
	//initializeRobot();

	//waitForStart();
ungripGoal();
wait1Msec(50);
goBackInches(110,70);
wait1Msec(50);
turnLeftDegrees(1);
wait1Msec(50);
goBackInches(45,70);
wait1Msec(50);
gripGoal();
wait1Msec(50);
goInches(35,70);
wait1Msec(50);
goInches(5,70);
wait1Msec(50);
turnRightDegrees(160);
wait1Msec(50);
//goBackInches(90,70);
//wait1Msec(50);


}
