#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C2_1,     motorTR,       tmotorTetrix, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorTL,       tmotorTetrix, openLoop, driveLeft, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorPulley,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorb,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motora,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorBrush,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S3_C1_1,    servoHingeL,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servoHingeR,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servoBasket,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servoBlocker,         tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int tickTest2 = nMotorEncoder[motorTL];
//int time = timer1;


void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}
void turnLeftDegrees(int degree)
{
	int tickGoal = degree * 8;
	int tickTest = nMotorEncoder[motorBL];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = -60;
		motor[motorTR] = 60;
		motor[motorBL] = -60;
		motor[motorBR] = 60;

		tickTest = abs(nMotorEncoder[motorBL]);

	}
}

void turnRightDegrees(int degree)
{
	int tickGoal = degree * 8;
	int tickTest = nMotorEncoder[motorBL];

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = 60;
		motor[motorTR] = -60;
		motor[motorBL] = 60;
		motor[motorBR] = -60;

		tickTest = nMotorEncoder[motorBL];
	}
}

void goInches(int inch, int speed)
{
	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	int tickGoal = 67 * inch;
	int tickTest = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = speed;
		motor[motorTR] = speed;
		motor[motorBL] = speed;
		motor[motorBR] = speed;

		tickTest = nMotorEncoder[motorBL];
	}
}

void goBackInches(int inch, int speed)
{

	//reset encoders
	nMotorEncoder[motorTR] = 0;
	nMotorEncoder[motorTL] = 0;
	nMotorEncoder[motorBR] = 0;
	nMotorEncoder[motorBL] = 0;

	int tickGoal = 67 * inch;
	int tickTest = 0;

	//move forward until encoder reading is more than the goal
	while(tickTest < tickGoal)
	{
		motor[motorTL] = -speed;
		motor[motorTR] = -speed;
		motor[motorBL] = -speed;
		motor[motorBR] = -speed;

		tickTest = abs(nMotorEncoder[motorBL]);

	}
		motor[motorTL] = 0;
		motor[motorTR] = 0;
		motor[motorBL] = 0;
		motor[motorBR] = 0;
}


void gripGoal()
{
	//Bring the grips down
	servo[servoHingeL] = 0; //CHANGE VALUES LATER
	servo[servoHingeR] = 255;
}

void ungripGoal()
{
	//Grip loosens around the goal
	servo[servoHingeL] = 120; //CHANGE VALUES LATER
	servo[servoHingeR] = 120;
}



/* TASKS TO DO- BLUE
	1. Move off of ramp [20 points]
	2. Go to goal
	3. Grab goal
	4. Move goal to parking zone [20 points]
*/

//set robot up backwards
task main()
{
	//initializeRobot();

 //waitForStart();

		ungripGoal();
		wait1Msec(250);

	//Move backward off ramp
		goBackInches(113,70);
		wait1Msec(50);
		goBackInches(4,50);
		wait1Msec(50);
		goBackInches(2,40);

	//grip goal
		gripGoal();
		wait1Msec(250);

	//turn and go to parking zone
		turnRightDegrees(20);
		wait1Msec(50);

		goInches(25,70);
		wait1Msec(50);

		goInches(0,0);
		wait1Msec(300);

		turnRightDegrees(195);
		wait1Msec(600);

		//turnRightDegrees(25);
		//wait1Msec(50);

		goBackInches(0,0);
		wait1Msec(100);

		goBackInches(60,70);
		wait1Msec(50);

		turnRightDegrees(35);
		wait1Msec(50);

		goBackInches(40,70);
		wait1Msec(50);

		//turnLeftDegrees(30);
		//wait1Msec(50);
		//goBackInches(20,70);
		//wait1Msec(50);

//	while(true)
//{
//	nxtDisplayCenteredTextLine(3, "Time: %d", timer1);
//	wait1Msec(50);
//}

//while(true)
//{
//	nxtDisplayCenteredTextLine(5, "tickTest: %d",nMotorEncoder[motorTL]);
//	wait1Msec(50);
//}
	//score ball
	//servo[servoBasket] = 255;
	//motor[motorPulley] = 70;
	//wait1Msec(4000);
	//servo[servoBasket] = 70 ;
	//move to parking zone
		//gripGoal();
		//turnRightDegrees(30);
		//wait1Msec(5);
		//goinches(5,60);
		//wait1Msec(5);
		//goInches(10,30);
		//turnRightDegrees(130);
		//wait1Msec(5);
		//turnRightDegrees(55);
		//wait1Msec(5);
	//score ball in two different goals
	//One ball is in basket already, one ball is in between the sponge brushes.
	//Score one ball, lower the basket again, bring the other ball up, score that one in another goal

	//grip and score from basket in one goal
	//gripGoal();

	//turn, move forward and then score in second goal

	//drive to parking zone pushing goal one

}
